Space Mission: lcd.c File Reference
lcd.c File Reference
#include <htc.h>
#include "lcd.h"
Macros
#define _XTAL_FREQ 8000000
Unless specified elsewhere, 8MHz system frequency is assumed.
#define lcd_cursor(x) lcd_write(((x)&0x7F)|0x80)
#define LCD_RS RB4
#define LCD_EN RB5
#define LCD_DATA PORTB
#define LCD_STROBE() ((LCD_EN = 1),(LCD_EN=0))
Functions
void lcd_write (unsigned char c)
void lcd_clear (void)
void lcd_puts (const char *s)
void lcd_putch (char c)
void lcd_goto (unsigned char pos)
void lcd_init ()
void LCD_build (unsigned char location, unsigned char *ptr)
Detailed Description
LCD interface example Uses routines from delay.c This code will interface to a standard LCD controller like the Hitachi HD44780. It uses it in 4 bit mode, with the hardware connected as follows (the standard 14 pin LCD connector is used):
PORTB bits 0-3 are connected to the LCD data bits 4-7 (high nibble) PORTB bit 4 is connected to the LCD RS input (register select) PORTA bit 5 is connected to the LCD EN bit (enable)
To use these routines, set up the port I/O (TRISB) then call lcd_init(), then other routines as required.
Function Documentation
void LCD_build (unsigned char location, unsigned char * ptr)
load a custom characters
Parameters
location position of the custom character
ptr array that drow the custom character
References LCD_RS, and lcd_write().
void lcd_clear (void)
Clear and home the LCD
References LCD_RS, and lcd_write().
void lcd_goto (unsigned char pos)
Go to the specified position
References LCD_RS, and lcd_write().
void lcd_init (void)
initialise the LCD - put into 4 bit mode
References lcd_clear(), LCD_RS, and lcd_write().
void lcd_putch (char c)
write one character to the LCD
References LCD_RS, and lcd_write().
void lcd_puts (const char * s)
write a string of chars to the LCD
References LCD_RS, and lcd_write().
void lcd_write (unsigned char c)
write a byte to the LCD in 4 bit mode