Space Mission: lcd.h File Reference
lcd.h File Reference
Defines
#define RIGA1 0
#define RIGA2 0x40
#define lcd_cursor(x) lcd_write(((x)&0x7F)|0x80)
Functions
void lcd_write (unsigned char)
void lcd_clear (void)
void lcd_puts (const char *s)
void lcd_goto (unsigned char pos)
void lcd_init (void)
void lcd_putch (char)
void LCD_build (unsigned char, unsigned char *)
Detailed Description
LCD interface header file See lcd.c for more info
Function Documentation
void LCD_build (unsigned char location, unsigned char * ptr)
load a custom characters
Parameters:
location position of the custom character
ptr array that drow the custom character
References LCD_RS, and lcd_write().
void lcd_clear (void)
Clear and home the LCD
References LCD_RS, and lcd_write().
void lcd_goto (unsigned char pos)
Go to the specified position
References LCD_RS, and lcd_write().
void lcd_init (void)
intialize the LCD - call before anything else
initialise the LCD - put into 4 bit mode
References lcd_clear(), LCD_RS, and lcd_write().
void lcd_putch (char c)
write one character to the LCD
References LCD_RS, and lcd_write().
void lcd_puts (const char * s)
write a string of characters to the LCD
write a string of chars to the LCD
References LCD_RS, and lcd_write().
void lcd_write (unsigned char c)
write a byte to the LCD in 4 bit mode