Space Mission: spaceMission.c File Reference
spaceMission.c File Reference
File containing implementation of spaceMission.
#include <pic.h>
#include "lcd.h"
Macros
#define DIVIDER 25
Approximate divider used to trigger a timer every second on a 8Mhz processor.
#define LCD_RS RB4
Pin used to enable the display.
#define CHERRYPOINTS 10
Points added when a cherry is catched by the spacecraft.
#define EMPTY '\x20'
Empty space referencecharacter.
#define ASTEROIDS '\x02'
Asteroids reference.
#define CHERRY '\x03'
Cherry reference.
#define SPACECRAFT '\x01'
Spacecraft reference.
#define ENDGAME 0x01
First bit: 1 if the game ended.
#define COLLISION 0x02
Second bit: 1 if a collision has been detected.
#define POSITION 0x04
Third bit: 1 if the spacecraft is in the lower line of the screen.
#define UPDATE 0x08
Fourth bit: 1 if the screen need to be refreshed.
Functions
__CONFIG (0x23E2)
Configure PIC compiler.
void interrupt isr (void)
Interrupts handling routine.
void sleep ()
Helper function, used to wait for a small period of time.
void displayDigits ()
Puts the digit representation of the value to be shown into the four 7-bit leds, using the map array.
void displaySpace ()
Puts the content of the space (line0 and line1) on the LCD display.
unsigned char generateAsteroid ()
Return 1 or 0 randomly (black magic), in order to generate or not a new asteroid.
unsigned char generateCherry ()
Return 1 or 0 randomly (black magic), in order to generate or not a new cherry.
void checkCollision ()
Check for a collision with an asteroid or a cherry The spacecraft collides with something if:
void updateSpace ()
Update the asteroids and the score points.
void initCountDown ()
Initialize timer, prescaler and interrupt stuff.
int pow (int b, int exp)
void endMission ()
int main ()
Variables
const unsigned char cherry [] ={0x2,0x4,0xe,0x15,0x11,0x11,0xe}
Empty space character implementation.
const unsigned char spacecraft [] ={0x0,0x10,0x1c,0x1b,0x1c,0x10,0x0}
Asteroids character implementation.
const unsigned char asteroid [] ={0x4,0xe,0x1e,0xf,0x1e,0x1c,0x4}
Cherry character implementation.
const unsigned char sad [] ={0x0,0x2,0x14,0x4,0x14,0x2,0x0}
Spacecraft character implementation.
unsigned char status = 0
Mask of bits to store boolean variables of status of the game.
const unsigned char map [] ={63,6,91,79,102,109,125,7,127,111}
Map used to encode a 7-digits display.
unsigned char c1
Character 1 to be written in the LED Display of 7 bits.
unsigned char c2
Character 2 to be written in the LED Display of 7 bits.
unsigned char c3
Character 3 to be written in the LED Display of 7 bits.
unsigned char c4
Character 4 to be written in the LED Display of 7 bits.
unsigned char refDivider = 25
Set the space updating speed.
unsigned char updateDivider = 0
Counter of timer interrupt related to refDivider.
unsigned char divider = 0
Counter of timer interrupt related to DIVIDER.
unsigned char countdown = 100
Countdown to the end of the game.
unsigned int points = 0
Points gained by the player.
char line0 [16] =" "
Content of display Line 0.
char line1 [16] =" "
Content of display Line 1.
unsigned char indexLines
Pointer of the circular buffer.
Detailed Description
File containing implementation of spaceMission.
Author
Carminati, Ferroni, Martucci, Polino
Date
9 May 2014
Function Documentation
void checkCollision ()
Check for a collision with an asteroid or a cherry The spacecraft collides with something if:
it's in position 1 and there's an object in line 1;
it's in position 0 and there's an object in line 0. If the collision is with a cherry, points are incremented by CHERRYPOINTS
References ASTEROIDS, CHERRY, CHERRYPOINTS, COLLISION, EMPTY, indexLines, line0, line1, points, POSITION, and status.
void endMission ()
Display a message after the end of the game. Shows points gained and a "Game Over" message.
References lcd_clear(), lcd_goto(), lcd_puts(), points, and pow().
void interrupt isr (void)
Interrupts handling routine.
This routine is used to handle timing logic. updateDivider is incremented at every iteration until it reaches the refDivider: the space environment is then shifted by one position. divider is incremented at every iteration until it reaches the DIVIDER: the countdown time is then decremented by one
References c3, c4, countdown, DIVIDER, divider, ENDGAME, refDivider, status, UPDATE, and updateDivider.
int main ()
Main of the program. Initialize registers, clear the LCD display and initialize the countDown stuff. The main loop:
displays asteroids and shows them on LCD display, if something changed;
checks if countdown reached 0 or the spacecraft collided with an asteroid;
checks if a button up has been pressed and pushes up the spacecraft;
checks if a button down has been pressed and pushes down the spacecraft;
polls the ADC to set asteroids speed;
displays side digits (points and countDown).
References asteroid, checkCollision(), cherry, COLLISION, displayDigits(), displaySpace(), ENDGAME, endMission(), initCountDown(), LCD_build(), lcd_clear(), lcd_init(), lcd_puts(), POSITION, refDivider, sad, sleep(), spacecraft, status, UPDATE, and updateSpace().
int pow (int b, int exp)
Compute the power with base b and exponent exp (b^exp)
Parameters
b base
exp exponent
Returns
b^e
void updateSpace ()
Update the asteroids and the score points.
This function use 2 "circular" buffers (one for each line) of 16 digits each (line1 and line0)
Increments the points when an asteroids reach the end of the line.
Generate a new asteroid randomly on line0[indexLines] if no asteroid have been generated on line1[prevIndex] and vice-versa to avoid impossible paths for the spacecraft.
Generates randomly a cherry instead of an asteroids
Check for collisions
References ASTEROIDS, c1, c2, checkCollision(), generateAsteroid(), generateCherry(), indexLines, line0, line1, and points.